# Generated by Django 2.2.7 on 2019-12-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Image',
        ),
    ]
